# Use an official Node.js image as the base image
FROM node:22.9.0-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache make gcc g++ python3

# Copy package.json for efficient layer caching
COPY ["package.json", "./"]


# Copy source code (excluding node_modules thanks to .dockerignore)
COPY . .

# Install dependencies and rebuild bcrypt
RUN npm install && \
    npm rebuild bcrypt --build-from-source 

# Run the app in development mode using nodemon
CMD ["npm", "run", "debug"]
